# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 501e80f386c25e23147f21ca7bce0c5265e571b149166f6771ccd8e224018c9b90f52d95df2bc2e945b10f54b86c1735dc417b34ac9769851381b9f072c26f6e

test:
  secret_key_base: 85c3dc91e17c3e08a062a4fbb62bcf6bc011feef40cb6a88f625fd6048762de17177e306f92388892e476fda7c08ac3f4975aa8039b2efa10d2e7bdfe13efa67

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
